#!/bin/sh

# copy built files to ftp server on web6

# first parameter is the filename, don't need anything else
# look for RPMS/i386/... and SRPMS

USER=sjmudd
HOST=web6.dialin.co.uk
SRC=/usr/src/redhat
DST=/usr/home/sjmudd/public_html/postfix

echo copying $1.src.rpm to $HOST:$DST/SRPMS
scp $SRC/SRPMS/$1.src.rpm $USER@$HOST:$DST/SRPMS/
echo copying $1.386.rpm to $HOST:$DST/RPMS/i386
scp $SRC/RPMS/i386/$1.i386.rpm $USER@$HOST:$DST/RPMS/i386/
