#!/bin/sh
#
#  $Id: make-postfix.spec,v 1.11 2000/12/31 20:50:48 root Exp $
#

POSTFIX_SUFFIX=
POSTFIX_CCARGS=
POSTFIX_AUXLIBS=
POSTFIX_REQUIRES=
REDHAT_PREREQ=
REDHAT_RELEASE='Unknown Linux Distribution'

# RedHat 6.2 and later include LDAP support, earlier versions don't
# For this reason LDAP support is not compiled by default

echo ""
echo "Generating Postfix spec file: ../SPECS/postfix.spec"
if [ "X$POSTFIX_LDAP" = "X1" ]; then
    echo "  adding LDAP support to spec file"
    POSTFIX_SUFFIX="${POSTFIX_SUFFIX}+ldap"
    POSTFIX_CCARGS="${POSTFIX_CCARGS} -DHAS_LDAP"
    POSTFIX_AUXLIBS="${POSTFIX_AUXLIBS} -L/usr/lib -lldap -llber"
    POSTFIX_REQUIRES="openldap >= 1.2.9"
    POSTFIX_BUILDREQUIRES="openldap-devel >= 1.2.9"
fi
if [ "X$POSTFIX_PCRE" = "X1" ]; then
    echo "  adding PCRE support to spec file"
    POSTFIX_CCARGS="${POSTFIX_CCARGS} -DHAS_PCRE"
    POSTFIX_AUXLIBS="${POSTFIX_AUXLIBS} -lpcre"
    POSTFIX_SUFFIX="${POSTFIX_SUFFIX}+pcre"
    POSTFIX_REQUIRES="${POSTFIX_REQUIRES},pcre"
    POSTFIX_BUILDREQUIRES="${POSTFIX_BUILDREQUIRES},pcre"
fi
if [ "X$POSTFIX_MYSQL" = "X1" ]; then
    echo "  adding MySQL support to spec file"
    POSTFIX_SUFFIX="${POSTFIX_SUFFIX}+mysql"
    POSTFIX_CCARGS="${POSTFIX_CCARGS} -DHAS_MYSQL -I/usr/include/mysql"
    POSTFIX_AUXLIBS="${POSTFIX_AUXLIBS} -L/usr/lib/mysql -lmysqlclient -lm"
    POSTFIX_REQUIRES="${POSTFIX_REQUIRES},MySQL,MySQL-client"
    POSTFIX_BUILDREQUIRES="${POSTFIX_BUILDREQUIRES},MySQL,MySQL-client"
fi
if [ "X$POSTFIX_SASL" = "X1" ]; then
    echo "  adding SASL support to spec file"
    POSTFIX_SUFFIX="${POSTFIX_SUFFIX}+sasl"
    POSTFIX_CCARGS="${POSTFIX_CCARGS} -DUSE_SASL_AUTH"
    POSTFIX_AUXLIBS="${POSTFIX_AUXLIBS} -lsasl"
    POSTFIX_REQUIRES="${POSTFIX_REQUIRES},cyrus-sasl"
    POSTFIX_BUILDREQUIRES="${POSTFIX_BUILDREQUIRES},cyrus-sasl"
fi

# rh7 db3 crap - this is rather ugly
if [ `rpm -q redhat-release` ]; then
    # We are running RedHat Linux
    # check for RedHat 7 and change Requires for new db3 if necessary
    A=`rpm -q redhat-release | grep -q 7; echo $?`
    if [ "X$A" = "X0" ]; then
        POSTFIX_REQUIRES="${POSTFIX_REQUIRES},db3"
        POSTFIX_BUILDREQUIRES="${POSTFIX_BUILDREQUIRES},db3,db3-devel"
        REDHAT_PREREQ=', /etc/init.d'
    fi
    REDHAT_RELEASE=`rpm -q redhat-release` 
fi

if [ ! -z "$POSTFIX_REQUIRES" ]; then
    POSTFIX_REQUIRES="Requires: ${POSTFIX_REQUIRES}"
fi
if [ ! -z "$POSTFIX_BUILDREQUIRES" ]; then
    POSTFIX_BUILDREQUIRES="BuildRequires: ${POSTFIX_BUILDREQUIRES}"
fi

cat > ../SPECS/postfix.spec <<EOF
##############################################################################
#
# W A R N I N G -- DO NOT EDIT THIS FILE -- W A R N I N G
#
# It is generated automatically from postfix.spec.in
# in the SOURCES directory.
#
# If you need to make changes do them to the postfix.spec.in
# file and regenerate the spec file with
#
#     cd ../SOURCES
#     sh make-postfix.spec
#
# after defining the relevent options you wish to use in
# the spec file
#
# This spec file generated with the following options:
#
# POSTFIX_SMTPD_MULTILINE_GREETING=$POSTFIX_SMTPD_MULTILINE_GREETING
# POSTFIX_SAFE_MYNETWORKLS=$POSTFIX_SAFE_MYNETWORKS
# POSTFIX_BROKEN_AUTH=$POSTFIX_BROKEN_AUTH
# POSTFIX_LDAP=$POSTFIX_LDAP
# POSTFIX_PCRE=$POSTFIX_PCRE
# POSTFIX_MYSQL=$POSTFIX_MYSQL
# POSTFIX_SASL=$POSTFIX_SASL
#
# Built on $REDHAT_RELEASE
#
EOF
sed "
s!__POSTFIX_SUFFIX__!$POSTFIX_SUFFIX!g
s!__POSTFIX_CCARGS__!$POSTFIX_CCARGS!g
s!__POSTFIX_AUXLIBS__!$POSTFIX_AUXLIBS!g
s!__POSTFIX_REQUIRES__!$POSTFIX_REQUIRES!g
s!__POSTFIX_BUILDREQUIRES__!$POSTFIX_BUILDREQUIRES!g
s!__REDHAT_RELEASE__!$REDHAT_RELEASE!g
s!__REDHAT_PREREQ__!$REDHAT_PREREQ!g
" postfix.spec.in >> ../SPECS/postfix.spec

#echo " "
#
#( cd ../SPECS; rpm -ba postfix.spec )
