#!/bin/sh
#
#  $Id: make-postfix.spec,v 1.22.2.1 2001/03/30 16:11:16 sjmudd Exp $
#

SUFFIX=
REQUIRES=
BUILDREQUIRES=
DISTRIBUTION_PREREQ=
DISTRIBUTION='Unknown Linux Distribution'

# Ensure only one of POSTFIX_MYSQL and POSTFIX_REDHAT_MYSQL are defined
test -n "$POSTFIX_MYSQL" && \
  test -n "$POSTFIX_REDHAT_MYSQL" && {
    cat <<EOF
Postfix MySQL support
---------------------

There are MySQL packages available from two different sources built with
different package names.  According to the MySQL package you are using
choose to set _ONE_ of the following environment variables accordingly:

POSTFIX_MYSQL = 1	# MySQL packages named MySQL... from www.mysql.com
POSTFIX_REDHAT_MYSQL = 1# MySQL packages named mysql... from RedHat (7+)

Please set the appropriate value and rerun make-postfix.spec again
EOF
    exit 1
}

# RedHat 6.2 and later include LDAP support, earlier versions don't
# For this reason LDAP support is not compiled by default

echo ""
echo "Generating Postfix spec file: ../SPECS/postfix.spec"
if [ "$POSTFIX_LDAP" = 1 ]; then
    echo "  adding LDAP  support to spec file"
    SUFFIX="${SUFFIX}+ldap"
fi
if [ "$POSTFIX_PCRE" = 1 ]; then
    echo "  adding PCRE  support to spec file"
    SUFFIX="${SUFFIX}+pcre"
fi
if [ "$POSTFIX_MYSQL" = 1 ]; then
    POSTFIX_REDHAT_MYSQL=0
    echo "  adding MySQL support (www.mysql.com MySQL* packages) to spec file"
    SUFFIX="${SUFFIX}+MySQL"
fi
if [ "$POSTFIX_REDHAT_MYSQL" = 1 ]; then
    POSTFIX_MYSQL=0
    echo "  adding MySQL support (RedHat mysql* packages) to spec file"
    SUFFIX="${SUFFIX}+mysql"
fi
if [ "$POSTFIX_SASL" = 1 ]; then
    echo "  adding SASL  support to spec file"
    SUFFIX="${SUFFIX}+sasl"
fi
if [ "$POSTFIX_TLS" = 1 ]; then
    echo "  adding TLS support to spec file"
    SUFFIX="${SUFFIX}+tls"
fi

# rh7 db3 crap - this is rather ugly
if [ `rpm -q redhat-release` ]; then
    # We are running RedHat Linux
    # check for RedHat 7 and change Requires for new db3 if necessary
    A=`rpm -q redhat-release | grep -q 7; echo $?`
    if [ "$A" = 0 ]; then
        REQUIRES="Requires: db3"
        BUILDREQUIRES="BuildRequires: db3, db3-devel"
        DISTRIBUTION_PREREQ=', /etc/init.d, /sbin/service'
    fi
    DISTRIBUTION=`rpm -q redhat-release` 
    # check for RedHat 6 and change SUFFIX to avoid package name conflicts
    A=`rpm -q redhat-release | grep -q 6; echo $?`
    if [ "$A" = 0 ]; then
        SUFFIX="rh6${SUFFIX}"
    fi
fi

# ensure if undefined the value is 0
if [ -z "$POSTFIX_LDAP" ]; then
    POSTFIX_LDAP=0
fi
if [ -z "$POSTFIX_MYSQL" ]; then
    POSTFIX_MYSQL=0
fi
if [ -z "$POSTFIX_REDHAT_MYSQL" ]; then
    POSTFIX_REDHAT_MYSQL=0
fi
if [ -z "$POSTFIX_PCRE" ]; then
    POSTFIX_PCRE=0
fi
if [ -z "$POSTFIX_SASL" ]; then
    POSTFIX_SASL=0
fi
if [ -z "$POSTFIX_TLS" ]; then
    POSTFIX_TLS=0
fi
if [ -z "$POSTFIX_SMTPD_MULTILINE_GREETING" ]; then
    POSTFIX_SMTPD_MULTILINE_GREETING=0
fi

# Remove leading '+' from package suffix (if exists)
SUFFIX=`echo "${SUFFIX}" | sed -e 's;^\+;;'`

cat > ../SPECS/postfix.spec <<EOF
##############################################################################
#
# W A R N I N G -- DO NOT EDIT THIS FILE -- W A R N I N G
#
# It is generated automatically from postfix.spec.in in the SOURCES directory.
#
EOF
sed "
s!__DISTRIBUTION_PREREQ__!$DISTRIBUTION_PREREQ!g
s!__DISTRIBUTION__!$DISTRIBUTION!g

s!__SMTPD_MULTILINE_GREETING__!$POSTFIX_SMTPD_MULTILINE_GREETING!g

s!__REQUIRES__!$REQUIRES!g
s!__BUILDREQUIRES__!$BUILDREQUIRES!g

s!__SUFFIX__!$SUFFIX!g

s!__LDAP__!$POSTFIX_LDAP!g
s!__MYSQL__!$POSTFIX_MYSQL!g
s!__REDHAT_MYSQL__!$POSTFIX_REDHAT_MYSQL!g
s!__PCRE__!$POSTFIX_PCRE!g
s!__SASL__!$POSTFIX_SASL!g
s!__TLS__!$POSTFIX_TLS!g
" postfix.spec.in >> ../SPECS/postfix.spec

# end of make-postfix.spec
