#!/bin/sh
# $Revision: 2.3.2.1 $
# File to make links from this directory to the SOURCES directory for all files

HERE=`pwd`
BASE=/usr/src/redhat/SOURCES

echo Linking files to directory $BASE
for i in `cat postfix-filelist`; do
  test -f $i && test ! -x $i && \
    ln -s $HERE/$i $BASE/$i && echo "  $i"
done
