#!/bin/sh
#
#  $Id: make-postfix.spec,v 1.3 2000/12/22 15:55:02 root Exp $

POSTFIX_SUFFIX=
POSTFIX_CCARGS=
POSTFIX_AUXLIBS=

# supposedly redhat now include LDAP libraries in the default install, so
# include LDAP support by default
POSTFIX_LDAP=1

echo "Generating Postfix spec file: ../postfix.spec"
if [ "X$POSTFIX_LDAP" = "X1" ]; then
    echo "adding LDAP support to spec file"
#   if it's the default don't add it to the name
#   POSTFIX_SUFFIX="${POSTFIX_SUFFIX}+ldap"
    POSTFIX_CCARGS="${POSTFIX_CCARGS} -I/usr/local/include -DHAS_LDAP"
    POSTFIX_AUXLIBS="${POSTFIX_AUXLIBS} -L/usr/lib -lldap -llber"
fi
if [ "X$POSTFIX_PCRE" = "X1" ]; then
    echo "adding PCRE support to spec file"
    POSTFIX_CCARGS="${POSTFIX_CCARGS} -DHAS_PCRE"
    POSTFIX_AUXLIBS="${POSTFIX_AUXLIBS} -lpcre"
    POSTFIX_SUFFIX="${POSTFIX_SUFFIX}+pcre"
fi
if [ "X$POSTFIX_MYSQL" = "X1" ]; then
    echo "adding MySQL support to spec file"
    POSTFIX_SUFFIX="${POSTFIX_SUFFIX}+mysql"
#   POSTFIX_CCARGS=${POSTFIX_CCARGS} ...fix me..."
#   POSTFIX_AUXLIBS="${POSTFIX_AUXLIBS} ...fix me..."
fi
if [ "X$POSTFIX_SASL" = "X1" ]; then
    echo "adding SASL support to spec file"
    POSTFIX_SUFFIX="${POSTFIX_SUFFIX}+sasl"
    POSTFIX_CCARGS="${POSTFIX_CCARGS} -DUSE_SASL_AUTH"
    POSTFIX_AUXLIBS="${POSTFIX_AUXLIBS} -lsasl"
fi

cat > ../SPECS/postfix.spec <<EOF
##############################################################################
#
# W A R N I N G -- DO NOT EDIT THIS FILE -- W A R N I N G
#
# It is generated automatically from postfix.spec.in
# in the SOURCES directory.
#
# If you need to make changes do them to the postfix.spec.in
# file and regenerate the spec file with
#
#     cd ../SOURCES
#     sh make-postfix.spec
#
# after defining the relevent options you wish to use in
# the spec file
#
# This spec file genreated with the following options:
#
# POSTFIX_SMTPD_MULTILINE_GREETING=$POSTFIX_SMTPD_MULTILINE_GREETING
# POSTFIX_SAFE_MYNETWORKLS=$POSTFIX_SAFE_MYNETWORKS
# POSTFIX_LDAP=$POSTFIX_LDAP
# POSTFIX_PCRE=$POSTFIX_PCRE
# POSTFIX_MYSQL=$POSTFIX_MYSQL
# POSTFIX_SASL=$POSTFIX_SASL
#
EOF
sed "
s!XX_POSTFIX_SUFFIX!$POSTFIX_SUFFIX!g
s!XX_POSTFIX_CCARGS!$POSTFIX_CCARGS!g
s!XX_POSTFIX_AUXLIBS!$POSTFIX_AUXLIBS!g
" postfix.spec.in >> ../SPECS/postfix.spec
