#!/bin/sh
#
# $Header: /home/sjmudd/tmp/cvsroot/postfix-rpm/Attic/move-files,v 1.1.4.1 2007/05/04 20:51:25 sjmudd Exp $
#
# move files from their location after building to ftp site.

#Wrote: /home/sjmudd/RPM/PKG/postfix-2.4.1-2.rhel4.src.rpm
#Wrote: /home/sjmudd/RPM/PKG/postfix-2.4.1-2.rhel4.i386.rpm

VER=2.4
BUILDDIR=/home/sjmudd/RPM/PKG/
cd $BUILDDIR || exit 1

BINPATTERN="postfix-$VER\.[0-9]-[0-9][0-9]*\.rh(el)?[0-9][0-9]*\.i386\.rpm"
SRCPATTERN="postfix-$VER\.[0-9]-[0-9][0-9]*\.rh(el)?[0-9][0-9]*\.src\.rpm"

echo "BINPATTERN=$BINPATTERN"
for file in $(ls | egrep "$BINPATTERN")
do
	#echo file=$file
	distribution=$(ls "$file" | sed -e 's/\.i386\.rpm//' -e 's/^.*\.//')
	#echo distribution=$distribution
	destdir=/home/mirror/ftp.wl0.org/official/$VER/RPMS-$distribution-i386/
	#echo destdir=$destdir

	if ! [ -f $destdir$file ]; then
		echo "Moving file $file to $destdir"
		mv $file $destdir
	fi
done
for file in $(ls | egrep "$SRCPATTERN")
do
	#echo file=$file
	distribution=$(ls "$file" | sed -e 's/\.src\.rpm//' -e 's/^.*\.//')
	#echo distribution=$distribution
	destdir=/home/mirror/ftp.wl0.org/official/$VER/SRPMS
	#echo destdir=$destdir
	destfile=$(echo $file | sed -e "s/\.$distribution//")
	#echo destfile=$destfile

	#echo "$destdir/$destfile"
	if ! [ -f $destdir/$destfile ]; then
		echo "Moving file $file to $destdir/$destfile"
		mv $file $destdir/$destfile
	fi
done
