#!/bin/sh
#
# postfix-get-distribution - Simple script to determine the correct
# distribution, in the form <distribution>-<major>.<minor>
#
# - there appears to be no clear way of doing this which is cross platform
#   compatible between different rpm vendors
#
# With rh9 the return value of rpm -q redhat-release does not include a
# minor version.  This is used in several places in make-postfix.spec so we
# generate a minor version of 0 if necessary.

# Added fedora to the supported distributions.

# Provide a usage message
function usage () {
id='$Revision: 1.2.2.10 $'
id=$(echo $id | sed -e 's/^.*: //g' -e 's/ .*$//g')
cat <<EOF
`basename $0` $id

Copyright (C) 2002-2003 - Simon J Mudd <sjmudd@pobox.com>
This program may be freely redistributed under the terms of the GNU GPL

Usage: `basename $0` [--help] [--full] [--distribution] [--major] [--minor]

Return the distribution name in the form of <distribution>-<major>.<minor>
or optionally provide ONE of the components.
EOF
}

info=full
if [ -n "$1" ]; then
    case $1 in
    --distribution) info=distribution;;
    --major) info=major;;
    --minor) info=minor;;
    --full)  ;;# do nothing
    --help) usage; exit 0;;
    *) usage; exit 1;;
    esac
fi

#
# Get release information (if possible)
if [ `rpm -q redhat-release >/dev/null 2>&1; echo $?` = 0 ]; then
    releasename=redhat
    release=`rpm -q redhat-release | sed -e 's;^redhat-release-;;' \
                                         -e 's;-[0-9]*$;;'`
elif [ `rpm -q fedora-release >/dev/null 2>&1; echo $?` = 0 ]; then
    releasename=fedora
    release=`rpm -q fedora-release | sed -e 's;^fedora-release-;;' \
                                         -e 's;-[0-9]*$;;'`
elif [ `rpm -q redhat-release-es >/dev/null 2>&1; echo $?` = 0 ]; then
    releasename=rhes
    release=`rpm -q redhat-release-es | sed -e 's;^redhat-release-es-;;' \
                                            -e 's;[A-Z]*-[0-9]*$;;'`
elif [ `rpm -q redhat-release-as >/dev/null 2>&1; echo $?` = 0 ]; then
    releasename=rhas
    release=`rpm -q redhat-release-as | sed -e 's;^redhat-release-as-;;' \
                                            -e 's;[A-Z]*-[0-9]*$;;'`
elif [ `rpm -q mandrake-release >/dev/null 2>&1; echo $?` = 0 ]; then
    releasename=mandrake
    release=`rpm -q mandrake-release | sed -e 's;^mandrake-release-;;' \
                                           -e 's;-[0-9]*mdk$;;'`
elif [ `rpm -q yellowdog-release >/dev/null 2>&1; echo $?` = 0 ]; then
    releasename=yellowdog
    release=`rpm -q yellowdog-release | sed -e 's;^yellowdog-release-;;' \
                                            -e 's;-[0-9]*$;;'`
else
    releasename=unknown
    release=0.0
fi

echo $release | grep -q '\.' && {
    # there's a '.' in release (e.g. 8.0)
    major=`echo $release | sed -e 's;\.[0-9]*$;;'`
    minor=`echo $release | sed -e 's;^[0-9]*\.;;'`
} || {
    # there's no '.' in release (e.g. 9)
    major=$release
    minor=0
}

#echo releasename=$releasename
#echo release=$release
#echo major=$major
#echo minor=$minor

case $info in
full)
    echo ${releasename}-${major}.${minor};;
distribution)
    echo ${releasename};;
major)
    echo ${major};;
minor)
    echo ${minor};;
*)
    echo "Internal error info=$info" >&2
    exit 1
esac
