#!/bin/sh
#
# $Revision: 2.4 $
#
# Simple script to build postfix.  Note please read make-postfix.spec
# for more information on how to setup alternative build options.
#

set -e
echo "Building postfix..."
PWD=`pwd`

cd `rpm --eval '%{_sourcedir}'`
sh make-postfix.spec
cd `rpm --eval '%{_specdir}'`
rpm -ba postfix.spec
cd ${PWD}
