#!/bin/sh
#
# $Revision: 2.1 $
#
# Simple script to build postfix.  Note please read make-postfix.spec
# for more information on how to setup alternative build options.
#

set -e
echo "Building postfix..."
PWD=`pwd`

cd /usr/src/redhat/SOURCES
sh make-postfix.spec
cd /usr/src/redhat/SPECS
rpm -ba postfix.spec
cd ${PWD}
