#!/bin/sh
# $Revision: 2.5 $
# Simple script to make links from this directory to the SOURCES directory for all files

quiet=0
USAGE="Usage: $0 [--quiet]
    --quiet                 Be quiet about removing the links.

Remove the links from the current directory to %{_sourcedir}
for the files listed in postfix-filelist.  "
 
# Process command-line options and parameter settings.
for arg
do
    case $arg in
     --quiet) quiet=1;;
           *) echo $0: Error: $USAGE 1>&2; exit 1;;
    esac
    shift
done


HERE=`pwd`
sourcedir=`rpm --eval '%{_sourcedir}'`

[ "${quiet}" = 0 ] && echo "Removing links from ${sourcedir}"
for file in `cat postfix-filelist`; do
  test -L ${sourcedir}/${file} && test -f ${file} && rm ${sourcedir}/${file} && [ "${quiet}" = 0 ] && echo "	${file}"
done
