#!/bin/sh
# $Revision: 2.1 $
# File to make links from this directory to the SOURCES directory for all files

HERE=`pwd`
BASE=/usr/src/redhat/SOURCES

echo Removing links from $BASE
for i in *; do
  if [ -f $i && -L $BASE/$i ]; then
    rm $BASE/$i && echo $i
  fi
done
