#!/bin/sh
#
# This script sets up the rpm environment I use to build my packages
# Namely:
# - rpmmacros copied to ~/.rpmmacros if it doesn't exist
# - cvs and rpm directory structure within $HOME based on the rpmmacros
#   installed previously

msg_debug () {
    [ -n "${DEBUG}" ] && echo "$*"
}
msg_info () {
    echo "$*"
}
msg_warn () {
    echo "warning: $*" >&2
}
msg_err () {
    echo "error: $*" >&2
    exit 1
}

myname=$(basename $0)
msg_debug "$myname: started"

[ $(id -u) = 0 ] && msg_err "This script is intented to be run as a non-root user"

# create a ~/cvs subdirectory to put the cvs files
# I use postfix-current, postfix-2.1, postfix-2.0, postfix-1.1 by renaming
# postfix-rpm after checking out the appropriate tree.

msg_info "checking for directory ~/cvs"
[ ! -d ~/cvs ] && {
    mkdir ~/cvs && msg_info "- Creating directory ~/cvs" || \
	msg_warn "- could not create directory ~/cvs"
} || msg_info "- directory exists: OK"

# check if ~/.rpmmacros exists, DON'T overwrite it.
msg_info "checking for file ~/.rpmmacros"
[ ! -e ~/.rpmmacros ] && {
    cp rpmmacros ~/.rpmmacros && \
	msg_info "- Installing default RPM Macros file..." || \
	msg_warn "- Could not copy rpmmacros to ~/.rpmmacros"
} || {
    msg_info "- RPM macros already installed in ~/.rpmmacros (not overwriting)"
    msg_info "- consider using file rpmmacros or comparing the 2 files"
}

for param in _topdir _sourcedir _specdir _tmppath _builddir \
	 _srcrpmdir _rpmdir; do
    dir=$(rpm --eval "%{$param}" | sed -e 's;%{name};postfix;')
    msg_info "checking for directory $dir"
    [ ! -d "$dir" ] && {
        mkdir -p $dir && msg_info "- Creating directory $dir" || \
		msg_warn "- Could not create directory $dir"
    } || msg_info "- Directory exists: OK"
done

