#!/bin/sh
#
# Shell script to test the build of my package
# Takes 2 parameters:
# - POSTFIX_XXXX   the POSTFIX_ variable to set when checking the patches
# - the value to set it to (1 if not given)
#
# Return value: the result of the rpmbuild -bp execution

[ -n "$DEBUG" ] && set -x

umask 022
PATH=/bin:/usr/bin:/usr/sbin:/usr/etc:/sbin:/etc:/usr/contrib/bin:/usr/gnu/bin:/usr/ucb:/usr/bsd
SHELL=/bin/sh
 
NAME=$1
VALUE=${2:-1}

srcdir=$(rpm --eval '%{_sourcedir}' | sed -e 's;%{name};postfix;')
specdir=$(rpm --eval '%{_specdir}' | sed -e 's;%{name};postfix;')
buildresults=results.${NAME}

# delete previous file
[ -f $buildresults ] && rm $buildresults

sh linkfiles --quiet --delete

(
# start the build
eval unset $NAME && \
eval $NAME=$VALUE && \
eval export $NAME && \
sh linkfiles --create && \
cd ${srcdir} && \
sh make-postfix.spec && \
cd ${specdir} && \
rpmbuild -bp postfix.spec
) > ${buildresults} 2>&1

RC=$?

sh linkfiles --quiet --delete

exit $RC
