#!/bin/sh
#
# Shell script to test the build of my package
# Takes 2 parameters:
# - POSTFIX_XXXX   the POSTFIX_ variable to set when checking the patches
# - the value to set it to (1 if not given)
#
# Return value: the result of the rpmbuild -bp execution

umask 022
PATH=/bin:/usr/bin:/usr/sbin:/usr/etc:/sbin:/etc:/usr/contrib/bin:/usr/gnu/bin:/usr/ucb:/usr/bsd
SHELL=/bin/sh
 
current_directory=`pwd`
parametername=$1
parametervalue=${2:-1}

srcdir=`rpm --eval '%{_sourcedir}'`
specdir=`rpm --eval '%{_specdir}'`
pwd=`pwd`

( cd ${srcdir} && \
    eval unset $parametername && \
    eval $parametername=$parametervalue && \
    eval export $parametername && \
    sh make-postfix.spec && \
    cd ${specdir} && \
    rpmbuild -bp postfix.spec ) >/dev/null 2>&1
