#!/bin/sh
#
# $Header: /home/sjmudd/tmp/cvsroot/postfix-rpm/test-patches,v 2.1.4.3 2004/07/20 21:31:28 sjmudd Exp $
#

test_patch () {
    echo -n "===> testing $1 ... "
    sh test-one-patch $1 $2
    rc=$?
    if [ $rc = "0" ]
    then
        echo PASSED
    else
        depends=
        grep -q "is needed by postfix" results.$1 && depends="[check installed dependencies]"
        echo "FAILED $depends"
    fi
}

[ -n "$DEBUG" ] && set -x

# Test all the patches in the package and check which ones apply cleanly
myname=$(basename $0)

cat <<EOF

$myname: Postfix RPM patch tester

Results of building with different patches
------------------------------------------

EOF

test_patch POSTFIX_CDB 1
test_patch POSTFIX_IPV6 1
test_patch POSTFIX_LDAP 1
test_patch POSTFIX_PCRE 1
test_patch POSTFIX_PGSQL 1
test_patch POSTFIX_SASL 2
test_patch POSTFIX_SMTPD_MULTILINE_GREETING 1
test_patch POSTFIX_TLS 1
test_patch POSTFIX_VDA 1

cat <<EOF
---------------

NOTES:
[1] Check build outputs for each failed patch and ensure that all dependencies
    are installed.
[2] Patches are not tested together

EOF
